import axios, { Endpoints } from './endpoints';
import {
  login,
  signUp,
  getDashboardData,
  deleteEquipment,
  addNewEquipment,
  getFertilizers,
  getSeeds,
  getEquipments,
  generateUrl,
  getPosts,
  deletePost,
  commentOnPost,
  newPost,
  fetchCropsLearn,
} from './helper';

export {
  axios,
  Endpoints,
  login,
  signUp,
  getDashboardData,
  deleteEquipment,
  addNewEquipment,
  getFertilizers,
  getSeeds,
  getEquipments,
  generateUrl,
  getPosts,
  deletePost,
  commentOnPost,
  newPost,
  fetchCropsLearn,
};
